### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by dhavalsoni1928** [AustinChou/KYDrawerController-ObjC#2]
Sometimes app just crashes when i try to setMainViewController. I have total of 10 items in drawer view which contains tableview. Can you give me and example of it integration. i guess may be i am missing something in my implmentation. Thanks

**Comment by evianzhow** [comment]
@dhavalsoni1928 Please check https://github.com/ykyouhei/KYDrawerController for examples. This repo is just a replica of swift version, including the same logic. 
For this moment, we have to guess it is not an Objective-C only issue.
