### ISSUE TITLE
pushViewController not working

### ISSUE THREAD

**Issue by girubhai** [AustinChou/KYDrawerController-ObjC#3]
Hi,Thanks for your library.
As given in example(Menu UITableViewController's **didSelectRowAtIndexPath** method),there is view background color change on menu items clicked but how to go to another view controller instead of changing view of same viewcontroller.
As I did 
`[self.navigationController pushViewController:secondViewController animated:YES];
`
but it is not working.Any suggestion?

**Comment by evianzhow** [comment]
From menu view controller, 
`KYDrawerController *elDrawer = (KYDrawerController*)self.navigationController.parentViewController;`
will get the drawer controller, then, use `elDrawer.mainViewController` to get your main view controller, it might likely to be an UINavigationController instance, then do the push.

**Comment by evianzhow** [comment]
@girubhai Please reply to this issue if the problem still confuses you or this issue will be closed in 3 days.

**Comment by girubhai** [comment]
@AustinChou Thanks to reply,now its working.
