### ISSUE TITLE
open drawer on click of menu button 

### ISSUE THREAD

**Issue by harshadmadaye** [AustinChou/KYDrawerController-ObjC#4]
i'm trying to open the drawer without sliding, just by clicking on some button from my main VC. please help me solve this.
i tried setDrawerState from KYDrawerController , compiler goes through all code but nothing happens on UI.

**Comment by evianzhow** [comment]
This issue might be helpful to you. https://github.com/EvianZhow/KYDrawerController-ObjC/issues/3
